name: Hackathon PR Previews
author: bazottie
description: Deploy preview links on own hosting
runs:
  using: node16
  main: 'dist/index.mjs'
branding:
  icon: cloud-lightning
  color: orange
inputs:
  GITHUB_TOKEN:
    description: GitHub token with access to the repo
    required: true
    default: ''