name: CI
on: [pull_request, workflow_dispatch]
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Comment hello world
        uses: ./
        with:
          GITHUB_TOKEN: ${{ github.token }}